### ISSUE TITLE
UI Audit: Documentation Generator/HTML Template

### ISSUE THREAD

**Issue by mcturco** [asyncapi/design-system#10]
#### Reason/Context
In order to understand what is working and what is not working as far as the UI of the documentation template, auditing all of the current design patterns and visual styles might help us to define the problems that are present in the current UI and help us to define a new design system.

The findings of this audit will help us to start working on the smaller components of 1 of 3 design systems needed for the initiative. This design system will be for `Documentation Generator` until we decide on a better name for this design system as well as its parent system and sisters.

#### How will this audit be carried out?
The audit will be completed in figma by re-creating the components from the UI and sorting the components based on usage. From there, we should be able to define inconsistencies as well as noting any design patterns that exist currently.

Here is the working Figma file to follow along --> https://www.figma.com/file/S4TVyXHCYblq8SykRhKhAz/AsyncAPI-Documentation-UI-Audit?node-id=2%3A2

**Comment by mcturco** [comment]
# UI/UX Audit
Below is an audit of problems that I noticed in the current UI of the AsyncAPI visual documentation components. I encourage you to share your thoughts on the report below or something else that you noticed in the UI that can be improved. 

[View this report on my notion -->](https://missyturco.notion.site/Docs-generator-UI-audit-23bacc33b3b04a10aea453236bcccad8)
[View Figma file of audited UI -->](https://www.figma.com/file/S4TVyXHCYblq8SykRhKhAz/Documentation-UI-Audit?node-id=2%3A2)

## Goals for this audit
- View all of the existing UI at a glance
- Identify problems/inconsistencies with the UI based on audit
- Use problems to leverage solutions to create brand new UI
- Use this audit to define some UX inconsistencies/potential problems as well

---

## Problems identified

### Problem # 1

Typography doesn’t match between markdown (in Info Object) and various typography within the AsyncAPI documentation

---

### Problem # 2

Outputted sidebar component contrast ratio is not AAA compliant

<img width="713" alt="Screen Shot 2022-03-21 at 3 41 23 PM" src="https://user-images.githubusercontent.com/60163079/163821670-d98adff3-61f6-412b-b3c1-e9d98ab52437.png">
A11y Compliance test done in Figma

---

### Problem # 3

Notice how dropdown button arrows are not centered to the text (could also be an illusion because the text is normal case)

![Screen Shot 2022-03-31 at 1 31 57 PM](https://user-images.githubusercontent.com/60163079/163821810-aec2aec1-7757-456d-b57c-5636e65e6e82.png)
Right arrow appears to be situated just above the center line of the text

---

### Problem # 4

There seems to be no clear color palette, which might make it hard for users to apply their own brand colors to the generated docs

---

### Problem # 5

This tag has two different types of spacing, which I don’t believe was intentional

<img width="187" alt="Screen Shot 2022-03-21 at 3 49 06 PM" src="https://user-images.githubusercontent.com/60163079/163821895-d526c276-6827-402b-830e-2a123cf55656.png">
**Tag version 1:** More top and bottom padding

<img width="125" alt="Screen Shot 2022-03-21 at 3 49 11 PM" src="https://user-images.githubusercontent.com/60163079/163821933-8d631a5a-e409-41b5-80bd-ac2f71fc4a68.png">
**Tag version 2:** Less top and bottom padding, more left and right padding

---

### Problem # 6

Tags look more like buttons, and there is no clear distinction between a clickable tag and a non-clickable tag

![Screen Shot 2022-03-31 at 1 37 57 PM](https://user-images.githubusercontent.com/60163079/163822002-a6ac6b04-d035-4603-bc34-f3941e63246e.png)
You can’t tell which ones are buttons and which ones are tags

---

### Problem # 7

General inconsistencies with tag formatting, such as padding, type size, type weight, text transform, border colors, etc. No unified tag language.

![Screen Shot 2022-03-31 at 1 40 27 PM](https://user-images.githubusercontent.com/60163079/163822060-f6f8a13b-b544-4cba-a1b3-40b3aea9ded6.png)
Screenshot of all audited tags in the existing UI

---

### Problem # 8

PUB/SUB labels type styles and size/spacing are inconsistent

![Screen Shot 2022-03-31 at 1 41 41 PM](https://user-images.githubusercontent.com/60163079/163822110-291c3ff2-f23a-466c-8d98-da31c47e8e17.png)
Screenshot of audited PUB/SUB operation labels that exist in the current UI

---

### Problem # 9

[More of a question rather than a stated problem]: Does this operation information need to be expandable/collapsible?

<img width="334" alt="Screen Shot 2022-03-21 at 3 51 22 PM" src="https://user-images.githubusercontent.com/60163079/163822204-7a4acc96-c0b3-490d-9dbf-9e6684acb436.png">
Example of expandable/collapsible UI, Screenshot from the actual UI in the application

---

### Problem # 10

[UX Note]: Is the `Schemas` section of the documentation UI necessary? While necessary in the spec, is it useful for the EDA consumer to see in the documentation or is it useful enough to see the message schema within the Message itself?

![Screen Shot 2022-03-31 at 1 56 57 PM](https://user-images.githubusercontent.com/60163079/163822278-efd0b718-f1fc-4f68-b2b2-d423cf90b72b.png)
Screenshot from the HTML template showing the `Schemas` section in the documentation

---

### Problem # 11

The inline code bock doesn’t show with expected formatting

![Screen Shot 2022-04-06 at 12 32 25 PM](https://user-images.githubusercontent.com/60163079/163822325-e64e283a-1ce4-4b30-be2a-69c2a32cacd1.png)
Screenshot of output when entering back ticks in markdown

**Comment by magicmatatjahu** [comment]
@mcturco Awesome audit. I can say, that current styles and components suck and it needs to be improved. I agree with you with all points. 

> [More of a question rather than a stated problem]: Does this operation information need to be expandable/collapsible?

You can have several `Operation specific information` for several bindings/protocols so you can end up with a very complex scheme of values that need to be scrolled, that's what the collapse button is for, but we can think about how to solve it better in the new design. Maybe through tabs? Each separate tab is a protocol, what do you think?

> [UX Note]: Is the Schemas section of the documentation UI necessary? While necessary in the spec, is it useful for the EDA consumer to see in the documentation or is it useful enough to see the message schema within the Message itself?

It represents all schemas that you use in your spec, but I agree with you that we if we show them in messages, then we can skip that section. We should remember about it.

**Comment by mcturco** [comment]
> @mcturco Awesome audit. I can say, that current styles and components suck and it needs to be improved. I agree with you with all points.

Thank you! 😄 I'm sure this is something that you and I will be working on together once we get far enough in the design

> You can have several Operation specific information for several bindings/protocols so you can end up with a very complex scheme of values that need to be scrolled, that's what the collapse button is for, but we can think about how to solve it better in the new design. Maybe through tabs? Each separate tab is a protocol, what do you think?

Gotcha, I will definitely consider this when designing the component for that. It might just have to end up being an expandable/collapsable UI component in the end, but I will see what we can do to make it better 😄 

> It represents all schemas that you use in your spec, but I agree with you that we if we show them in messages, then we can skip that section. We should remember about it.

Cool! Glad you agree, this is something that Fran mentioned once before as well.
