### ISSUE TITLE
Configure distribution of components

### ISSUE THREAD

**Issue by mcturco** [asyncapi/design-system#18]
#### Reason/Context
I think it is a good idea to start thinking about how we are going to use this repo to distribute the components to the repos that use them.

**Why do this now?**
We might want to do this now so that we can make code changes to the components from this repo and it would distribute those changes to all repos that use these components, that way we are making changes in one place versus several. It would also make it easier to iterate on components from here, which I think is the main reason to use Storybook in the first place.

Storybook has a page in their docs that describes how to set this up, I am assuming it is a similar method of the asyncapi react component? https://storybook.js.org/tutorials/design-systems-for-developers/react/en/distribute/

**Some other questions/thoughts that I have about this:**
- The design system will be worked on over time, so we will not yet have all components documented in the storybook at once. Does it make sense to finish a first version of the design system before we connect it to other repos?
- We could always document the components we have already on the website within this Storybook and then distribute the components as a package? Just a thought. I don't think that is a huge task from my perspective and could be done within a day - just copying and pasting the code for the components into this Storybook repo. They might not be documented right away, but at least all existing components would be included in the package.

@magicmatatjahu going to need your help on this one! 😄

**Comment by magicmatatjahu** [comment]
More about distribution https://github.com/asyncapi/design-system/pull/17#issuecomment-1075263264

**Comment by mcturco** [comment]
@magicmatatjahu 

> In react component we use semantic-release which automates the publishing of the component. It means we add a prefix to the commit name like feat: or fix: and we have a new version of our component on npm - fix to bump patch version (X.X.{this}), feat to minor (X.{this}.X).

Sounds good!

> I can take care of it if you want - or if you want to learn I can mentor you :)

I have a feeling that @yashsehgal might be interested in learning this part, but if not no worries. Even if he is not wanting to learn this process, I think I will still watch from the sidelines on this one 😄 I have a tendency of getting distracted from my actual tasks, but I will definitely look over your changes once it is implemented for learning purposes!

> But we have to remember, storybook serves rather as a documentation of components than publishing them, so storybook in this repo is something like addon for components, not main goal, main should be publishing to the npm.

From what I am reading in the storybook docs, it could serve as both a hub for designing/developing/testing components as well as documenting them, but I could be wrong! I have a call on Thursday with Postman's design system lead so I will remember to ask questions about their workflow and report back here!

**Comment by yashsehgal** [comment]
For sure @magicmatatjahu @mcturco I am willing to help you with this. Would love to learn how to properly structure the components.
