### ISSUE TITLE
Connect repo to Netlify

### ISSUE THREAD

**Issue by mcturco** [asyncapi/design-system#19]
#### Reason/Context
As mentioned by @magicmatatjahu, we should connect this repo to Netlify so we can preview PR changes easier in Storybook.

I personally don't know how to set this up, so any help would be appreciated!

**Comment by yashsehgal** [comment]
I would like to add this feature. Shall I get started?

Also, I know how to do the same thing with vercel, so if it's not mandatory to use netlify, I can setup a vercel deployment in the same manner.

What are your views on this @mcturco @magicmatatjahu ??

**Comment by mcturco** [comment]
Go for it @yashsehgal ! Definitely work with @magicmatatjahu or @smoya on this as I do not know the process that is involved to get this implemented. I suppose we should also connect this to a subdomain, something like `design-system.asyncapi.com` until we have a name for the design system, open to suggestions on this!

**Comment by smoya** [comment]
> Go for it @yashsehgal ! Definitely work with @magicmatatjahu or @smoya on this as I do not know the process that is involved to get this implemented. I suppose we should also connect this to a subdomain, something like `design-system.asyncapi.com` until we have a name for the design system, open to suggestions on this!

All our static websites are hosted in Netlify, where we have afaik some Pro account sponsored by them. You should ask @derberg or @fmvilas to create the site through Netlify UI. Besides this, you will probably want to create a `netlify.toml` file with a `build` section. See an example in [website repo](https://github.com/asyncapi/website/blob/master/netlify.toml#L6-L9).

Regarding the subdomain, same answer; @derberg or @fmvilas should do the magic if applies.

**Comment by magicmatatjahu** [comment]
For subdomain we can wait, but as @smoya wrote, Fran or Łukasz should connect this repo in Netlify dashboard and then we can create `netlify.toml` config file.

**Comment by yashsehgal** [comment]
Great then @magicmatatjahu 
I can start working on adding the `netlify.toml` module. Will let you know here, if I will face any issues.

**Comment by fmvilas** [comment]
I connected the repo to Netlify: https://enchanting-cascaron-aa83e8.netlify.app. So far it's not working, it's loading the default React app. You should work on the netlify.toml file to configure how to build the project correctly.

**Comment by magicmatatjahu** [comment]
@yashsehgal Now you can create PR with `netlify.toml` :)
