### ISSUE TITLE
Errors reported

### ISSUE THREAD

**Issue by naman-tiwari** [asyncapi/design-system#28]
[./.storybook/generated-stories-entry.js] 1.43 KiB {main} [built] [failed] [1 error]
[./.storybook/preview.js-generated-config-entry.js] 1.43 KiB {main} [built] [failed] [1 error]
[./.storybook/storybook-init-framework-entry.js] 1.43 KiB {main} [built] [failed] [1 error]

**Comment by yashsehgal** [comment]
Hey @naman-tiwari 
Thanks for raising an issue. May I know what set of commands did you run to execute the storybook?

The error log looks like some config-files or important modules are missing.
