### ISSUE TITLE
code review required

### ISSUE THREAD

**Issue by naman-tiwari** [asyncapi/design-system#30]
from line number 29506 to 29518 code review is required(update) and same therefore from line 53871 to 53876

_Originally posted by @naman-tiwari in https://github.com/asyncapi/design-system/pull/29#pullrequestreview-964515970_

**Comment by mcturco** [comment]
Hi @naman-tiwari! Please do not create issues for code review requests. Codeowners will automatically get a github notification when a review is required. Thanks!! 😄

**Comment by mcturco** [comment]
No worries!! 😄
