### ISSUE TITLE
[📑 Docs]: Adding logo to storybook page

### ISSUE THREAD

**Issue by yashsehgal** [asyncapi/design-system#8]
### What Dev Docs changes are you proposing?

We can try adding AsyncAPI's logo and title text in the storybook header instead of the default one, steps for doing the same has been explained [here](https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart)

Right now, the header has the default logo + title text
![image](https://user-images.githubusercontent.com/62352288/154414045-c1ed376e-8be8-4291-81dc-b6e9c2ba2376.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mcturco** [comment]
Agreed! Let's do it. The logo is in Figma in Visual Design > Brand > Logo
You should be able to export it from there, but let me know if you have trouble 😄

**Comment by yashsehgal** [comment]
I have added the SVG image in the Navbar and pushed the changes in the same `readme-sb` PR.
![image](https://user-images.githubusercontent.com/62352288/154536134-1c6d7603-e750-4f74-9b50-48caae4ecb7e.png)
